#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.config/brew/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global --file ~/.config/brew/Brewfile
  fi

  if [ ! -d "/Applications/iTerm.app" ] && [ ! -d "$HOME/Applications/iTerm.app" ]; then
    echo "Installing iTerm2"
    brew install --cask iterm2
  fi

  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

  if ([ -d "/Applications/Visual Studio Code.app" ] || [ -d "$HOME/Applications/Visual Studio Code.app" ]) && [ -f "$HOME/.config/vscode/settings.json" ]; then
    echo "Applying custom VSCode settings"
    mkdir -p "$HOME/Library/Application Support/Code/User"
    cp "$HOME/.config/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
  fi

fi